# Generated by Django 4.0.4 on 2022-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='group_name',
            field=models.CharField(choices=[('No Category', 'No Category')], default='No Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
