# Generated by Django 4.0.4 on 2022-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_group_description_group_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='desc',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='card',
            name='group_name',
            field=models.CharField(choices=[], default='No Category', max_length=100),
        ),
    ]
